apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
data:
  api.appsettings.json: |
    {
        "Logging": {
            "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
            }
        },
        "ConnectionStrings": {
            "Postgres": {{ .Values.config.connectionStrings.postgres | quote }}
        },
        "Jwt": {
            "Audience": {{ .Values.config.jwt.audience | quote }},
            "Authority": {{ .Values.config.jwt.authority | quote }},
            "RequireHttpsMetadata": {{ .Values.config.jwt.requireHttpsMetadata }}
        },
        "Auth0": {
            "Domain": {{ .Values.config.auth0.domain | quote }},
            "ClientId": {{ .Values.config.auth0.clientId | quote }},
            "ClientSecret": {{ .Values.config.auth0.clientSecret | quote }}
        },
        "CloudStorage": {
            "Cdn": {
                "Url": {{ .Values.config.cloudStorage.cdn.url | quote }},
                "Folders": {
                    "Images": "images"
                }
            },
            "Authentication": {
                "ConnectionString": {{ .Values.config.cloudStorage.authentication.connectionString | quote }}
            }
        },
        "ImageProcessing": {{ .Values.config.imageProcessing | toJson }}
    }
  cli.appsettings.json: |
    {
        "Logging": {
            "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
            }
        },
        "ConnectionStrings": {
            "Postgres": {{ .Values.config.connectionStrings.postgres | quote }}
        },
        "Auth0": {
            "Domain": {{ .Values.config.auth0.domain | quote }},
            "ClientId": {{ .Values.config.auth0.clientId | quote }},
            "ClientSecret": {{ .Values.config.auth0.clientSecret | quote }}
        }
    }